[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[build.nixpacksPlan.phases.install]
cmds = ["npm install -g pnpm", "pnpm install"]

[build.nixpacksPlan.phases.build]
cmds = ["pnpm build"]

[deploy]
startCommand = "node .next/standalone/server.js"
healthcheckPath = "/"
healthcheckTimeout = 300

[deploy.env]
PORT = "3000"
