[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[build.nixpacksPlan.phases.install]
cmds = ["npm install"]

[build.nixpacksPlan.phases.build]
cmds = ["npm run build"]

[deploy]
startCommand = "npx next start -H 0.0.0.0 -p ${PORT:-8888}"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
