[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.pnpm"]

[build.nixpacksPlan.phases.install]
cmds = ["pnpm install"]

[build.nixpacksPlan.phases.build]
cmds = ["pnpm build"]

[deploy]
startCommand = "node .next/standalone/server.js"

[deploy.env]
PORT = "3000"
HOSTNAME = "0.0.0.0"
